export type User = {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  phoneNumber: string;
  address: string;
  street: string;
  streetNumber: string;
  door: string;
  postalcode: string;
  city: string;
  country: string;
  currency: string;
  btcAddress: string;
  accountNumber: string;
  acccountry: string;
  swift: string;
  accName: string;
  otherInfo: string;
  refNumber: string;
  balance: number;
};

export type User2 = {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  phoneNumber?: string | null;
  address?: string | null;
  street?: string | null;
  streetNumber?: string | null;
  door?: string | null;
  postalcode?: string | null;
  city?: string | null;
  country?: string | null;
  currency: string | null;
  btcAddress: string | null;
  accountNumber: string | null;
  acccountry: string | null;
  swift: string | null;
  accName: string | null;
  otherInfo: string | null;
  refNumber: string | null;
  balance: number | null;
};
