import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../globals.css';
import Header from "@/app/_component/globalcomponent/Header";
import Footer from "@/app/_component/globalcomponent/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <div className="md:mt-40 mt-32 flex-grow">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
